B1rel: 1
M0a: 1
T1f: 1
T2f: 0.1
R: 10
M0b: 0.1
T1b: 1
T1D: 0.01
T2b: 1.e-5
pw: 0.001
dt: 0.0015
es: 0.006
tr: 3
turbo: 80
np: 4
nb: 10
btr: 0.1
btrlast: 0.001
fa_sat: 200
fa_rage: 5
FLAG_Sine_Modulation: "BP"
N_altern: 1
r_tukey: 0.3
outPrefix: ''
export: True
offset: 7000